# Default values for on-prem.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @param nameOverride String to override on-prem.name
## it would partially override generated name
##
nameOverride: ""
## @param fullnameOverride String to override on-prem.fullname
## it would fully override generated name
##
fullnameOverride: ""

server:
  # container deployment Image 
  image:
    repository: lyvt/decoding-sdk
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0"
    pullPolicy: Always

  # Server specs
  replicaCount: 1

  # Server deployment status
  status: {}

  # Server container specs
  containerPort: 8010

  args: [/home/speechuser/start_master.sh, -p, "8010"]

  resources: {}

  # Server container restart policy
  restartPolicy: Always

  # Server service
  service:
    ports:
      name: 8010
      servicePort: 8010
      targetPort: 8010
    status: 
      loadBalancer: {}

  # Ingress resource
  ingressResource:
    ingressClassName: nginx
    host: asr-project.com
    path: /
    pathType: Prefix
    port: 8010

worker:
  # Container deployment Image
  image:
    repository: lyvt/decoding-sdk
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0"
    pullPolicy: Always

  # Worker specs
  replicaCount: 1

  strategy: 
    type: Recreate

  # Worker deployment status
  status: {}

  # Worker container specs
  args: [/home/speechuser/start_worker.sh]

  env:
    MASTER: on-prem-server-service:8010
    MODEL_DIR: english

  # worker volume mounts
  volumeMount:
    # name: on-prem-worker-pvc
    mountPath: /opt/models/

  resources: {}

  # Worker container restart policy
  restartPolicy: Always

  # Worker storage class
  storageClass:
    provisioner: kubernetes.io/no-provisioner
    volumeBindingMode: WaitForFirstConsumer

  # Worker PVC
  PVC:
    accessModes: ReadWriteOnce
    size: 100Mi
    status: {}

  PV: 
    accessModes: ReadWriteOnce
    mountPath: /home/asr-user/worker1-dir/models
    size: 100Mi
    # Values to assign pod to specific node
    key: kubernetes.io/hostname
    operator: In
    nodeName: asr-serve000001
