apiVersion: apps/v1
kind: Deployment
metadata:
  name: decoding-sdk-worker
  labels:
    io.kompose.service: decoding-sdk-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: decoding-sdk-worker
  template:
    metadata:
      labels:
        io.kompose.service: decoding-sdk-worker
    spec:
      containers:
        - name: decoding-sdk-worker
          image: lyvt/decoding-sdk:1.0
          args:
            - /home/speechuser/start_worker.sh
          env:
            - name: MASTER
              value: decoding-sdk-server:8010
            - name: MODEL_DIR
              value: english
          volumeMounts:
            - mountPath: /opt/models/
              name: decoding-sdk-worker-claim0
          resources: {}
      restartPolicy: Always
      volumes:
        - name: decoding-sdk-worker-claim0
          persistentVolumeClaim:
            claimName: decoding-sdk-worker-claim0
status: {}
