# Server deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "on-prem.server.deployment.name" . }}
spec:
  replicas: {{ include "on-prem.server.replicaCount" . }}
  selector:
    matchLabels:
      podName: {{ include "on-prem.server.pod.name" . }}
  template:
    metadata:
      labels:
        podName: {{ include "on-prem.server.pod.name" . }}
    spec:
      containers:
        - name: {{ include "on-prem.server.container.name" . }}
          image: {{ include "on-prem.server.image.repository" . }}:{{ include "on-prem.server.image.tag" . }}
          imagePullPolicy: {{ include "on-prem.server.image.pullPolicy" . }}
          ports:
            - containerPort: {{ include "on-prem.server.containerPort" . }}
          args:
            {{- include "on-prem.server.args" . }}
          resources:
            limits: 
              memory: {{ include "on-prem.server.resources.limits.memory" . }}
            requests:
              cpu: {{ include "on-prem.server.resources.requests.cpu" . }}
              memory: {{ include "on-prem.server.resources.requests.memory" . }}
      restartPolicy: {{ include "on-prem.server.restartPolicy" . }}
status: {{ include "on-prem.server.status" . }}