apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "on-prem.worker.pvc.name" . }}
spec:
  storageClassName: {{ include "on-prem.worker.storageclass.name" . }}
  volumeName: {{ include "on-prem.worker.pv.name" . }}
  accessModes:
    - {{ include "on-prem.worker.PVC.accessModes" . }}
  resources:
    requests:
      storage: {{ include "on-prem.worker.PVC.size" . }}
status: {{ include "on-prem.worker.PVC.status" . }}
