apiVersion: v1
kind: Service
metadata:
  name: on-prem-server-service
spec:
  selector:
    podName: on-prem-server-pod
  ports:
    - name: "8010"
      port: 8010
      targetPort: 8010
status:
  loadBalancer: {}
    #ingress:
    #- ip: asr-project.com # or ip of the endpoints/ingress if DNS is not configured
