apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: on-prem-server-ingress-resource
spec:
  ingressClassName: nginx
  rules:
  - host: asr-project.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: on-prem-server-service
            port: 
              number: 8010