apiVersion: v1
kind: PersistentVolume
metadata:
  name: decoding-sdk-worker-persistentvolume
spec:
  storageClassName: decoding-sdk-worker-storageclass
  claimRef:
    name: decoding-sdk-worker-claim0
    namespace: default
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  local:
    path: /home/asr-user/worker1-dir/models
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - asr-serve000001