apiVersion: v1
kind: PersistentVolume
metadata:
  name: on-prem-worker-pv
spec:
  storageClassName: on-prem-worker-storageclass
  claimRef:
    name: on-prem-worker-pvc
    namespace: default
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/fyp-jonathan/worker1-dir/models #/home/asr-user/worker1-dir/models
  # Assign this pod to the worker-node
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - micl-server03 #asr-serve000001